Update models.py for compatibility with Django 2.0
`on_delete` will be mandatory in Django 2.0:

```
File "…/site-packages/pushy/models.py", line 74, in Device
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

- [Features removed in 2.0](https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0)